/* Content for the office and laptop desktop. Generated by tools/build_content.py from room_copy.yml
   and the main site's pages and data. Safe to edit by hand; see README.md. Links are relative to the
   site root and get index.html's data-site-base in front of them. */
window.ROOM_CONTENT = {
  "name": "Prof. Vaishali S. Ingale",
  "subtitle": "Assistant Professor · Information Technology · AIT Pune",
  "line": "Prof. Vaishali S. Ingale · Information Technology, AIT Pune",
  "tagline": "Machine learning, image analysis and information security. Teaching at AIT Pune since 2005.",
  "hint": "Click the laptop",
  "hintTouch": "Tap the laptop",
  "skipLabel": "Skip to pages",
  "skipUrl": "about/",
  "skipIntroLabel": "Skip intro",
  "standLabel": "Stand up",
  "loadingLabel": "Loading",
  "folders": [
    {
      "id": "about",
      "label": "About",
      "url": "about/",
      "link": "about/",
      "blurb": [
        "Assistant Professor, Information Technology, AIT Pune.",
        "At AIT since 2005."
      ],
      "portrait": true,
      "lead": "Prof. Vaishali S. Ingale is an Assistant Professor of Information Technology at the Army Institute of Technology (AIT), Pune. She has taught at AIT since July 2005.",
      "stats": [
        {
          "n": "18",
          "l": "papers"
        },
        {
          "n": "10",
          "l": "textbooks"
        },
        {
          "n": "21",
          "l": "years at AIT"
        },
        {
          "n": "43",
          "l": "citations"
        }
      ],
      "facts": [
        {
          "b": "Research interests",
          "t": "machine learning · deep learning for satellite and medical images · natural language processing · information security"
        },
        {
          "b": "Currently",
          "t": "Faculty In-Charge, AIT Open Source Software Club · Vice Branch Counsellor, IEEE AIT Student Branch"
        }
      ],
      "sections": [
        {
          "h": "Leadership and service",
          "link": "about/#leadership-and-service",
          "items": [
            "Conference Chair, ICNDIA-2026, the first edition of ICNDIA, an IEEE international conference hosted at AIT: 1,500+ submissions, 217 papers presented",
            "Faculty In-Charge, OSS Club and Innerve hackathon (9,500+ students, 2025)",
            "Mentor of both AIT first-prize teams, Smart India Hackathon 2024"
          ]
        },
        {
          "h": "Education",
          "link": "about/#education",
          "items": [
            "M.E., Computer Engineering, Pune University, 2008",
            "B.E., Computer Science and Engineering, SRTM University, 2002"
          ]
        }
      ]
    },
    {
      "id": "research",
      "label": "Research",
      "url": "about/#research",
      "link": "about/#research",
      "blurb": [
        "Machine learning for satellite and medical images.",
        "NLP and information security."
      ],
      "lead": "Applied machine learning, much of it co-authored with AIT students and colleagues.",
      "sections": [
        {
          "link": "about/#research",
          "items": [
            {
              "b": "Satellite images",
              "t": "maps, cloud masking, terrain features"
            },
            {
              "b": "Medical images",
              "t": "diabetic retinopathy grading with GNNs"
            },
            {
              "b": "Language",
              "t": "machine reading comprehension"
            },
            {
              "b": "Security",
              "t": "cyberattack prediction, cryptography, steganography"
            }
          ],
          "more": true
        },
        {
          "h": "Selected papers",
          "link": "publications/",
          "papers": [
            {
              "title": "Image to Image Translation: Generating Maps from Satellite Images",
              "meta": "arXiv preprint arXiv:2105.09253 · 2021",
              "href": "https://doi.org/10.48550/arXiv.2105.09253"
            },
            {
              "title": "Music Generation using Three-layered LSTM",
              "meta": "arXiv preprint arXiv:2105.09046 · 2021",
              "href": "https://doi.org/10.48550/arXiv.2105.09046"
            },
            {
              "title": "Cryptographic Steganography",
              "meta": "Computer Science & Information Technology (CS & IT): Fourth International Conference on Computational Science · 2014",
              "href": "https://doi.org/10.5121/csit.2014.4803"
            }
          ]
        }
      ]
    },
    {
      "id": "publications",
      "label": "Publications",
      "url": "publications/",
      "link": "publications/",
      "blurb": [
        "18 papers and chapters, 2013–2026.",
        "Springer, IEEE, arXiv and journals."
      ],
      "lead": "18 papers and chapters, 2013–2026.",
      "pubs": [
        {
          "title": "Automatic Extraction of Topographical Features from Satellite Images Using Deep Learning Methodologies",
          "meta": "Soft Computing and Its Engineering Applications (icSoftComp), Communications in Computer and Information Science",
          "year": 2026,
          "href": "https://doi.org/10.1007/978-3-032-22065-3_26"
        },
        {
          "title": "Diffusion-Based AI Model in Design Engineering for Text-to-3D CAD Generation: Comparative Study",
          "meta": "Recent Advances in Mechanical Engineering (FLAME 2024), Lecture Notes in Mechanical Engineering",
          "year": 2025,
          "href": "https://doi.org/10.1007/978-981-96-7480-0_7"
        },
        {
          "title": "Designing an Improved Cyberattack Prediction Model Using Context-Aware Behavioral Modeling Analysis",
          "meta": "Engineering, Technology & Applied Science Research",
          "year": 2025,
          "href": "https://doi.org/10.48084/etasr.11799"
        },
        {
          "title": "Classification of Diabetic Retinopathy Disease Using GNN",
          "meta": "2024 International Conference on Brain Computer Interface & Healthcare Technologies (iCon-BCIHT)",
          "year": 2024,
          "href": "https://doi.org/10.1109/iCon-BCIHT63907.2024.10882465"
        },
        {
          "title": "Cloud Image Masking on Satellite Images Using U-Net Architecture of Deep Learning",
          "meta": "2023 14th International Conference on Computing Communication and Networking Technologies (ICCCNT)",
          "year": 2023,
          "href": "https://doi.org/10.1109/ICCCNT56998.2023.10307645"
        },
        {
          "title": "Smart Attendance System",
          "meta": "Application of Communication Computational Intelligence and Learning",
          "year": 2022,
          "href": "https://doi.org/10.1201/9781003340867-7"
        },
        {
          "title": "Image to Image Translation: Generating Maps from Satellite Images",
          "meta": "arXiv preprint arXiv:2105.09253",
          "year": 2021,
          "href": "https://doi.org/10.48550/arXiv.2105.09253"
        },
        {
          "title": "Music Generation using Three-layered LSTM",
          "meta": "arXiv preprint arXiv:2105.09046",
          "year": 2021,
          "href": "https://doi.org/10.48550/arXiv.2105.09046"
        },
        {
          "title": "GenNet: Reading Comprehension with Multiple Choice Questions using Generation and Selection Model",
          "meta": "arXiv preprint arXiv:2003.04360",
          "year": 2020,
          "href": "https://doi.org/10.48550/arXiv.2003.04360"
        },
        {
          "title": "Datasets for Machine Reading Comprehension: A Literature Review",
          "meta": "SSRN Electronic Journal",
          "year": 2019,
          "href": "https://doi.org/10.2139/ssrn.3454037"
        },
        {
          "title": "Object Detection Using Convolution Neural Networks",
          "meta": "Proceedings of the International Conference on Communication and Information Processing (ICCIP), SSRN Electronic Journal",
          "year": 2019,
          "href": "https://doi.org/10.2139/ssrn.3422311"
        },
        {
          "title": "Headline Generation from News Article",
          "meta": "International Journal of Computer Engineering and Applications",
          "year": 2018,
          "href": ""
        },
        {
          "title": "Deportation of Market Manipulation using ADS",
          "meta": "International Journal of Advanced Research in Computer and Communication Engineering (IJARCCE)",
          "year": 2015,
          "href": "https://doi.org/10.17148/IJARCCE.2015.43152"
        },
        {
          "title": "A Survey on Authenticated Data Structure and Various Implementation Methods",
          "meta": "International Journal of Software and Web Sciences (IJSWS)",
          "year": 2015,
          "href": ""
        },
        {
          "title": "Cryptographic Steganography",
          "meta": "Computer Science & Information Technology (CS & IT): Fourth International Conference on Computational Science, Engineering and Information Technology (CCSEIT)",
          "year": 2014,
          "href": "https://doi.org/10.5121/csit.2014.4803"
        },
        {
          "title": "Configuration of Real Time Linux on EP93XX Platform",
          "meta": "International Journal of Advanced Research in Computer and Communication Engineering (IJARCCE)",
          "year": 2013,
          "href": "https://ijarcce.com/recent-issue-october-2013/"
        },
        {
          "title": "Porting of RTLinuxPro on ARM9 Platform",
          "meta": "International Journal of Engineering Research & Technology (IJERT)",
          "year": 2013,
          "href": "https://www.ijert.org/porting-of-rtlinuxpro-on-arm9-platform"
        },
        {
          "title": "Kunal Secure Astro-Encryption: Data Encryption and Compression Using Planar Geometry",
          "meta": "International Journal of Emerging Technologies in Computational and Applied Sciences (IJETCAS)",
          "year": 2013,
          "href": ""
        }
      ]
    },
    {
      "id": "leadership",
      "label": "Leadership & Service",
      "url": "leadership/",
      "link": "leadership/",
      "blurb": [
        "Conference Chair, ICNDIA-2026.",
        "OSS Club Faculty In-Charge; IEEE AIT SB."
      ],
      "lead": "Conference organisation, student branches, clubs and hackathon mentoring at AIT Pune.",
      "sections": [
        {
          "h": "ICNDIA-2026",
          "link": "leadership/#icndia-2026",
          "kicker": "September 2026 · Conference Chair",
          "p": "Conference Chair, with Dr. Ashwini Sapkal, of the first edition of ICNDIA, an IEEE international conference hosted at AIT.",
          "stats": [
            {
              "n": "1,500+",
              "l": "submissions"
            },
            {
              "n": "237",
              "l": "accepted"
            },
            {
              "n": "217",
              "l": "presented"
            },
            {
              "n": "6",
              "l": "parallel tracks"
            }
          ],
          "items": [
            "IEEE International Conference on Nexus of Digitalization, Intelligence and Applications",
            "18–19 September 2026, hybrid; organised by the Department of Information Technology, AIT",
            "Double-blind peer review; accepted and presented papers to be included in IEEE Xplore",
            "Inaugurated by Lt Gen Vipul Shinghal, Deputy Chief of Army Staff (IS&T); keynotes from IIIT Allahabad, COAI and DRDO"
          ],
          "more": true
        },
        {
          "h": "Open Source Software Club",
          "link": "leadership/#oss-club",
          "kicker": "Since 2016 · Innerve",
          "p": "Faculty In-Charge of AIT's OSS Club and its national hackathon, Innerve.",
          "stats": [
            {
              "n": "9,500+",
              "l": "students, Innerve 9.0"
            },
            {
              "n": "2,500+",
              "l": "teams, Innerve 9.0"
            },
            {
              "n": "₹12 lakh",
              "l": "prize pool, Innerve 9.0"
            },
            {
              "n": "10,000+",
              "l": "registrations, Innerve X"
            }
          ],
          "items": [
            "Co-in-charge: Prof. Kuldeep Hule",
            "Listed as staff in-charge on AIT's clubs page, 2018–19 to 2022–23",
            "Club founded 2014; also runs GRAPHICA, a first-year hackathon",
            {
              "b": "Innerve 7",
              "t": "(2023): judge"
            }
          ],
          "more": true
        },
        {
          "h": "IEEE AIT Student Branch",
          "link": "leadership/#ieee",
          "kicker": "Current · IEEE",
          "p": "Vice Branch Counsellor.",
          "items": [
            "Branch founded 16 July 2015; IEEE Pune Section, Region 10",
            "Collaborator on ICNDIA-2026"
          ]
        },
        {
          "h": "Smart India Hackathon 2024",
          "link": "leadership/#sih-2024",
          "kicker": "December 2024 · Mentor",
          "p": "Mentor, with Prof. Kuldeep Hule, of both AIT teams that won first prize at the grand finale.",
          "stats": [
            {
              "n": "2",
              "l": "first prizes"
            },
            {
              "n": "₹1,00,000",
              "l": "per team"
            }
          ],
          "items": [
            {
              "b": "Black Syndicate",
              "t": "(NIET, Greater Noida): cyber-triage tool, National Investigation Agency problem"
            },
            {
              "b": "Carbon Daters",
              "t": "(IIT Tirupati): innovation-indicators portal, Ministry of AYUSH and AIIA"
            }
          ]
        },
        {
          "h": "SPPU QIP grants",
          "link": "leadership/#sppu-qip",
          "kicker": "2017–2018 · Co-Investigator",
          "p": "Two SPPU Quality Improvement Programme grants, ₹1,00,000 each, for faculty programmes at AIT.",
          "items": [
            "Probability and Statistics for Machine Learning and Deep Learning, 5–9 December 2017",
            "Practical Approaches of Artificial Neural Network and Deep Learning, 17–19 December 2018"
          ]
        },
        {
          "h": "Faculty development",
          "link": "leadership/#resource-person",
          "kicker": "2015–2022",
          "items": [
            "SPPU resource person: Machine Learning & Laboratory Practices (TE IT, 2019 course), 26 July 2021",
            "SPPU resource person: Deep Learning and Lab Practices, 30 July 2022",
            "Paper setter, Machine Learning (2019 pattern, Sem I), October 2021",
            "Organised five faculty programmes at AIT, 2015–2022: cloud computing, ML and image processing, outcome-based education, deep learning on HPC, project management"
          ]
        }
      ]
    },
    {
      "id": "awards",
      "label": "Awards & Books",
      "url": "awards/",
      "link": "awards/",
      "blurb": [
        "Ten university textbooks.",
        "Best Teacher Award; published patent application."
      ],
      "lead": "Awards, patent, textbooks, certifications and memberships.",
      "sections": [
        {
          "h": "Awards",
          "link": "awards/#recognitions",
          "timeline": [
            {
              "y": "2020",
              "t": "Paper Presenter Award, CSI Annual Convention, KIIT Bhubaneswar"
            },
            {
              "y": "2016",
              "t": "Best Result Award, Design and Analysis of Algorithms (2014–15)"
            },
            {
              "y": "2013",
              "t": "Best Teacher Award (2011–12)"
            }
          ]
        },
        {
          "h": "Patent",
          "link": "awards/#patent",
          "p": "Interactive Shopping Experience Using Augmented Reality",
          "items": [
            "Indian patent application No. 202221075977",
            "Filed December 2022; published 13 January 2023"
          ]
        },
        {
          "h": "Textbooks",
          "link": "awards/#textbooks",
          "stats": [
            {
              "n": "10",
              "l": "university textbooks"
            },
            {
              "n": "2008–2022",
              "l": "Nirali Prakashan"
            }
          ],
          "items": [
            "Artificial Intelligence, SPPU: 2003, 2008 and 2015 patterns; Computer, IT and E&TC; 2022 TE Computer (ISBN 978-93-5451-491-3)",
            "Artificial Intelligence, BATU, 2020: two titles, one with Dr. Ashwini Sapkal",
            "Data Structures & Files, 2010: two editions"
          ]
        },
        {
          "h": "Certificates",
          "link": "awards/#certifications",
          "items": [
            {
              "b": "NPTEL",
              "t": "Programming in C, Design & Analysis of Algorithms (2015); Theory of Computation (2016); Machine Learning (2018); Python for Data Science (2019); NBA Accreditation and Teaching-Learning (2020); Introduction to Research (2021)"
            },
            {
              "b": "NVIDIA DLI",
              "t": "Fundamentals of Deep Learning for Multiple Data Types (2020)"
            }
          ]
        }
      ]
    },
    {
      "id": "teaching",
      "label": "Teaching",
      "url": "about/#teaching",
      "link": "about/#teaching",
      "blurb": [
        "Teaching at AIT since 2005.",
        "SPPU resource person in ML and DL."
      ],
      "lead": "Teaching at AIT since 2005.",
      "sections": [
        {
          "link": "about/#teaching",
          "items": [
            "10 university textbooks on AI and data structures (Nirali Prakashan, 2008–2022)",
            "SPPU resource person: ML labs (2021), DL labs (2022)",
            "Best Teacher Award (2011–12); Best Result Award, Design and Analysis of Algorithms (2014–15)"
          ]
        }
      ]
    },
    {
      "id": "cv",
      "label": "CV",
      "url": "cv/",
      "link": "cv/",
      "blurb": [
        "Education, experience, awards, certificates."
      ],
      "lead": "Assistant Professor of Information Technology at AIT Pune since 2005, working in machine learning, image analysis, NLP and information security. Author of ten university textbooks; Conference Chair, ICNDIA-2026.",
      "sections": [
        {
          "h": "Education",
          "items": [
            "M.E., Computer Engineering, Pune University, 2008",
            "B.E., Computer Science & Engineering, SRTM University, 2002"
          ]
        },
        {
          "h": "Experience",
          "kicker": "Assistant Professor, Department of Information Technology · since 2005",
          "items": [
            "Conference Chair, ICNDIA-2026, an IEEE international conference hosted at AIT (2026)",
            "Vice Branch Counsellor, IEEE AIT Student Branch",
            "Faculty In-Charge, Open Source Software Club and its hackathon Innerve",
            "Mentor, two first-prize teams, Smart India Hackathon 2024"
          ],
          "more": true
        },
        {
          "h": "Milestones",
          "timeline": [
            {
              "y": "2026",
              "t": "ICNDIA-2026. Conference Chair of the first edition of ICNDIA, an IEEE international conference hosted at AIT. 1,500+ submissions, 217 papers."
            },
            {
              "y": "2026",
              "t": "Satellite imagery paper. Springer (icSoftComp 2025). Deep learning to map roads, water and terrain."
            },
            {
              "y": "2025",
              "t": "Innerve 9.0. Faculty In-Charge. 9,500+ students, 2,500+ teams, ₹12 lakh prize pool."
            },
            {
              "y": "2024",
              "t": "Two first prizes at SIH. Mentored both AIT winning teams at Smart India Hackathon 2024."
            },
            {
              "y": "2023",
              "t": "Judge, Innerve 7. National hackathon of the AIT OSS Club."
            },
            {
              "y": "2023",
              "t": "Patent published. Indian application No. 202221075977, published 13 January 2023."
            },
            {
              "y": "2022",
              "t": "SPPU resource person. Deep Learning labs (2022) and Machine Learning labs (2021)."
            },
            {
              "y": "2020",
              "t": "CSI Paper Presenter Award. CSI Annual Convention 2020, KIIT Bhubaneswar."
            },
            {
              "y": "2018",
              "t": "Two SPPU QIP grants. Co-Investigator, ₹1,00,000 each, 2017 and 2018."
            },
            {
              "y": "2018",
              "t": "OSS Club. Listed as staff in-charge on AIT's clubs page, 2018–19 to 2022–23."
            },
            {
              "y": "2016",
              "t": "Best Result Award. Design and Analysis of Algorithms, 2014–15."
            },
            {
              "y": "2013",
              "t": "Best Teacher Award. For 2011–12."
            },
            {
              "y": "2008",
              "t": "M.E. and first textbook. M.E., Computer Engineering, Pune University. Ten textbooks by 2022."
            },
            {
              "y": "2006",
              "t": "Life Member, ISTE. Indian Society for Technical Education."
            },
            {
              "y": "2005",
              "t": "Joined AIT. Army Institute of Technology, Pune, 4 July 2005."
            },
            {
              "y": "2002",
              "t": "B.E.. Computer Science and Engineering, SRTM University."
            }
          ]
        }
      ]
    },
    {
      "id": "contact",
      "label": "Contact",
      "url": "mailto:vingale@aitpune.edu.in",
      "link": "mailto:vingale@aitpune.edu.in",
      "blurb": [
        "vingale@aitpune.edu.in",
        "IT Department, AIT, Dighi Hills, Pune 411015"
      ],
      "lead": "Army Institute of Technology, Dighi Hills, Alandi Road, Pune 411015, India",
      "links": [
        {
          "label": "Email",
          "value": "vingale@aitpune.edu.in",
          "href": "mailto:vingale@aitpune.edu.in"
        },
        {
          "label": "Google Scholar",
          "value": "Profile",
          "href": "https://scholar.google.com/citations?user=Ju77mncAAAAJ"
        },
        {
          "label": "ORCID",
          "value": "0000-0002-6750-6028",
          "href": "https://orcid.org/0000-0002-6750-6028"
        },
        {
          "label": "LinkedIn",
          "value": "Profile",
          "href": "https://www.linkedin.com/in/vaishali-ingale-72293314"
        }
      ]
    }
  ]
};
